version: "3"
services:
  # ------------------
  nginx:
    container_name: xw_nginx
    image: nginx:alpine
    ports:
      - "81:8011"
      - "5000:5000"
      - "6000:6000"
      - "80:80"
      - "443:443"
  # ------------------
  python:
    build: ./
    container_name: python_flask
    expose:
      - "5000"
      - "6000"
    volumes:
      - ./Flask:/root/
